name: Docker Image CI MSSQL

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: [ master ]
env:
  DOCKER_IMAGE: fallenreaper/eve-mssql
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Variables
        id: prepare
        run: |
          VERSION=$(date -u +'%Y%m%d') 
          
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          fi
          TAGS="${{ENV.DOCKER_IMAGE}}:${VERSION}"
          TAGS="$TAGS,${{ENV.DOCKER_IMAGE}}:latest"
          echo "TAGS=$TAGS" >> "$GITHUB_OUTPUT"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: success() && github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build and Push
        if: success() && github.event_name != 'pull_request'
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{steps.prepare.outputs.TAGS}}
          context: mssql/.
