name: Docker Image CI POSTGRES buildx

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: [ master ]
env:
  DOCKER_IMAGE: fallenreaper/eve-postgres
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        id: prepare
        run: |
          VERSION=$(date -u +'%Y%m%d') 

          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          fi
          TAGS="${{env.DOCKER_IMAGE}}:${VERSION}"
          TAGS="$TAGS,${{env.DOCKER_IMAGE}}:latest"
          echo "TAGS=$TAGS" >> "$GITHUB_OUTPUT"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/s390x,linux/arm/v7,linux/arm/v6
      - name: Login to DockerHub
        if: success() && github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Buildx (Build and Push)
        if: success() && github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{steps.prepare.outputs.TAGS}}
          platforms: linux/amd64,linux/arm64,linux/s390x,linux/arm/v7,linux/arm/v6
          context: postgres/.
      -
        name: Inspect image
        if: always() && github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{env.DOCKER_IMAGE}}:${{steps.prepare.outputs.version }}
