name: Docker Image CI POSTGRES buildx

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: master
env:
  DOCKER_IMAGE: fallenreaper/eve-postgres
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: |
          VERSION=$(date -u +'%Y%m%d') 

          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          fi

          TAGS="--tag ${{env.DOCKER_IMAGE}}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS --tag ${{env.DOCKER_IMAGE}}:latest"
          fi

          echo "version=$VERSION" >> "$GITHUB_OUTPUTS"
          echo "version=$VERSION"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          config-inline: |
            [worker.oci]
              platforms= [ "linux/amd64", "linux/arm64", "linux/arm/v7"]
      - name: Login to DockerHub
        if: success() && github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Buildx (Build and Push)
        if: success() && github.event_name != 'pull_request'
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{env.DOCKER_IMAGE}}:${{steps.prepare.outputs.version}}
          platforms: linux/amd64,linux/arm64,linux/s390x,linux/arm/v7,linux/arm/v6
          context: postgres/.
      -
        name: Inspect image
        if: always() && github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{env.DOCKER_IMAGE}}:${{steps.prepare.outputs.version }}
